package-lock.json, src/App.vue, src/assets/_custom.scss, src/components/CalendarDay.vue, src/components/JobHeader.vue, src/scss/_custom.scss, src/scss/app.scss
Style info, warnings and errors with colors to make them
better identifiable
=> Styling of info, warnings and errors

.env.development, .env.production
=> Add trailing slash to url

.env.production, deploy.sh, package-lock.json, package.json, public/404.html, src/components/JobHeader.vue, src/components/Logs.vue, src/components/Navigation.vue, src/main.js, src/views/Home.vue, src/views/Jobs.vue, vue.config.js
Publication on githuib pages requires a few changes:
- Set the base url (vus.config.js)
- Deploy to gh-pages branch (deploy.sh)
- Custom 404 to allow HTML history mode (404.html, Home.vue)
Some adjustments have been made to the layout of the app
to make it more usable on smart phones
=> Github pages deployment

src/components/CalendarDay.vue, src/components/JobCalendar.vue, src/components/JobHeader.vue, src/components/Logs.vue, src/components/Navigation.vue, src/graphql/queries.js, src/router.js, src/services/gob.js, src/views/Catalogues.vue, src/views/Entities.vue, src/views/Jobs.vue, tests/unit/gob.spec.js, tests/unit/queries.spec.js, vue.config.js
Quite a rewrite...
Use new jobs endpoint and dynamic loading of logs to improve performance
Loading indicator is used to show activity
=> Gui performance

.env.development, .env.production, default.conf, package-lock.json, package.json, src/components/StatusReport.vue, src/graphql/queries.js, src/services/sockets.js, src/views/Jobs.vue, tests/unit/queries.spec.js, vue.config.js
Triggered via a websocket connection with the backend
=> Show refresh button when new log messages become available

src/services/sockets.js
Connect using websocket protocol
Monitor socket events, print console messages
=> Improve websocket monitoring

default.conf
Allows for refresh of browser windows
without using #
in SPA application
=> HTML5 history mode

default.conf
Allows for refresh of browser windows
without using #
in SPA application
=> Release 2019-01-24

default.conf
=> Browser refresh

src/components/ServiceDetail.vue, src/graphql/queries.js, src/services/status.js
Now also works for multiple service instances
=> Update service status

src/views/Jobs.vue
Change filteredJobs from computed property to explicit calculated
data item
=> Fix filter bug

src/views/Jobs.vue
To prevent duplicate key
Also load jobs on startup and on refresh
=> Set unique key of jobs to jobid

src/components/FilterOverview.vue
Hide year, month, day in filter overview
These items are already shown on the calendar
=> Hide day in filter overview

package-lock.json, package.json, src/components/JobHeader.vue, src/components/Logs.vue, src/main.js, src/services/gob.js, src/views/Job.vue, src/views/Jobs.vue
Included moment-tz for timezone support
Use a custom filter to display datetimes in CET
=> Show date times in CET timezone

src/services/auth.js, src/services/gob.js, src/services/request.js, src/services/sockets.js
Changed the configuration to require login
Disable iframe check (otherwise updateToken won't work)
Improve logging
=> Allow for browser and token refresh

src/components/JobFilter.vue, src/views/Jobs.vue
Simple patch to allow to toggle the filters on the left
=> Toggle filters

src/components/JobFilter.vue, src/views/Jobs.vue
export_test can now be selected
filters are all lowercase
=> Solve issue with filters

src/components/ServiceDetail.vue
Show service threads grouped by name
Highlight services that are handling a message
=> Fix service overview

src/services/auth.js
Show a console warning when authorisation is disabled
=> Disable keycloak on localhost

src/views/Jobs.vue
API randomly returns empty array from time to time??
=> Retry get logs max 10 times

src/components/JobFilter.vue, src/components/Logs.vue, src/components/StatusIndicator.vue, src/views/Jobs.vue
Shortcut buttons span filter width
Logs overview rewritten to plain HTML table (fix render issues in ACC)
Status overview shows count of alive services
Fix render issue when jobs not yet loaded
=> Various updates

src/components/JobStart.vue, src/components/StatusReport.vue, src/services/gob.js, src/views/Management.vue
Start dump
Start action for multiple collections
Start relate for a specific attribute
Show running process in header
=> Iris improvements

package-lock.json, src/services/gob.js, src/views/Jobs.vue
Render per 20 jobs, only jobs that are visible
Prevent unnecessary sorting and filtering
Load only the last 7 days, instead of the last 10 days
=> Improve loading time

src/services/gob.js
Take filter into account
Return cached jobs if filter is equal to cached filter
=> Fix bug in jobs cache

src/components/Dashboard.vue, src/components/JobsSummary.vue
Have the jobs summary be a component
This reduces the already polluted dashboard view
=> Jobs Summary component

src/components/CalendarDay.vue, src/components/JobFilter.vue, src/components/JobHeader.vue, src/graphql/queries.js
This allows the jobs to be filtered on jobs that contain data warnings, errors or infos
=> Add data logging levels to management frontend

package-lock.json, src/services/gob.js, src/views/Jobs.vue
To correctly show recent prepare jobs.
Fix bug in url query update in jobs overview.
It was called 13 times instead of just once for every filter change
=> Include catalogue in jobId

package-lock.json, src/services/gob.js, src/views/Jobs.vue
To correctly show recent prepare jobs
=> Release catalogue in jobId

src/components/FilterItem.vue
=> Add random id to filter item

src/components/FilterItem.vue
=> Release add random id to filter item

src/App.css, src/components/dashboard/JobSummaries.js, src/components/jobs/JobHeader.js, src/components/jobs/JobLogs.js, src/components/jobs/JobsPage.js, src/components/jobs/JobsShortcuts.js, src/components/jobs/services/jobs.js, src/services/gob.js
Updated Job Header layout
Fixed a bug in date conversions by using ISO date formats
=> PGB 1345 job overview

src/components/dashboard/JobSummaries.js, src/components/jobs/JobsFilters.js, src/components/status/StatusIndicator.js, src/components/status/StatusOverview.js, src/components/status/index.js, src/components/status/status.css
Remove technical and test filter options
Fix tooltip for job summaries, status layout
=> Minor fixes

src/components/dashboard/JobSummaries.js, src/components/dashboard/LeadTimes.js, src/components/dashboard/dashboard.css, src/components/jobs/JobDetailPage.js, src/components/jobs/JobsShortcuts.js, src/components/management/JobStart.js
Show data consistency tests in dashboard
Uniform coloring of processes in dashboard.css
Job start fixed
Shortcuts fixed
=> Fixed several issues

src/components/dashboard/JobSummaries.js, src/components/dashboard/LeadTimes.js, src/components/dashboard/dashboard.css, src/components/jobs/JobDetailPage.js, src/components/jobs/JobsShortcuts.js, src/components/management/JobStart.js
Show data consistency tests in dashboard
Uniform coloring of processes in dashboard.css
Job start fixed
Shortcuts fixed
=> Release fix for several issues

package.json, src/components/dashboard/JobSummaries.js, src/components/dashboard/index.js, src/components/jobs/JobHeader.js, src/components/jobs/JobsFilterOverview.js, src/components/jobs/JobsFilters.js, src/components/jobs/JobsPage.js, src/components/jobs/JobsShortcuts.js, src/components/jobs/jobsSlice.js, src/components/jobs/services/jobs.js, src/services/auth.js, src/services/gob.js, src/services/gob.test.js, yarn.lock
De gebruiker kan kiezen tussen een overzicht van alle Jobs of van alle Processen
Binnen het overzicht van de processen kunnen de jobs van een process worden "opengeklapt"
=> PGB 2078 - Jobs groeperen per process

src/components/jobs/JobDetailPage.js
getJobs service returns service + jobs
[0] = service
[1,...] = jobs
For a single job: [0] = process, [1] = job
=> PGB 2206 job is te verwijderen in iris acceptatie zonder foutmelding

src/components/management/managementSlice.js
Add prepare action for WKPB and WOZ
=> Release 20201111

src/services/auth.js, src/services/auth.test.js
Use the acceptance realm of iam when running on test.
Using environment variables would be too big of a change for this moment and the required result
=> Add check for test environment

CODEOWNERS, yarn.lock
* npm packages updates.
* BenK CODEOWNERS.
=> npm packages updates. (#379)
